name: Github action demo
on: push
jobs: 
  Examples-actions-job:
    name: Exploring githu action
    runs-on: windows-latest
    steps:
    #display the event that trigger the worlflow
      runs: echo:"The JOB was trigrred by a ${{github.eventname}} event" 
